#!/bin/bash

echo "🔧 Alternative Sui CLI Installation Methods"
echo "=============================================="
echo ""
echo "The cargo installation failed. Here are alternative methods:"
echo ""

echo "METHOD 1: Download Pre-built Binary (Fastest)"
echo "----------------------------------------------"
echo "1. Visit: https://github.com/MystenLabs/sui/releases"
echo "2. Download the latest testnet release for Linux x86_64"
echo "3. Extract and move to PATH:"
echo "   tar -xzf sui-testnet-*.tgz"
echo "   sudo mv sui /usr/local/bin/"
echo "   chmod +x /usr/local/bin/sui"
echo ""

echo "METHOD 2: Use Docker (Recommended if issues persist)"
echo "----------------------------------------------------"
echo "docker pull mysten/sui-tools:testnet"
echo "docker run -it mysten/sui-tools:testnet sui --version"
echo ""

echo "METHOD 3: Build from source with more memory"
echo "--------------------------------------------"
echo "export CARGO_NET_GIT_FETCH_WITH_CLI=true"
echo "cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui"
echo ""

echo "METHOD 4: Use Sui Move Playground (No Installation)"
echo "---------------------------------------------------"
echo "1. Visit: https://play.sui.io/"
echo "2. Create new project"
echo "3. Copy the contract code from sui_contract/sources/student_nfts.move"
echo "4. Deploy directly from browser"
echo "5. Copy the Package ID and update src/utils/contract.ts"
echo ""

echo "=============================================="
echo "For METHOD 4 (Easiest - No CLI Required):"
echo "1. Open https://play.sui.io/ in your browser"
echo "2. Click 'New Project'"
echo "3. Replace the default code with our contract"
echo "4. Click 'Deploy' button"
echo "5. Copy the Package ID from the output"
echo "6. Update PACKAGE_ID in sui-student-nfts/src/utils/contract.ts"
echo ""
echo "This is the FASTEST way to get started!"
